name: settingsfrompullrequestwithandroidlocationmenu
description: This version has been forked from https://github.com/Libero793/settings and adds iOS method channel handler for openGPSSettings() method call.
author: Spencer <spencerccf@gmail.com>
homepage: https://github.com/plinkos/settings
version: 0.0.6

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ly.settingsfrompullrequestwithandroidlocationmenu
    pluginClass: SettingsPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"